# Generated by Django 6.0.8 on 2026-08-30 23:42

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), db_index=True)),
                ('to_instance', models.CharField(db_index=True, max_length=64)),
                ('from_instance', models.CharField(blank=True, max_length=64, null=True)),
                ('kind', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['to_instance', 'created_at'], name='evennia_mes_to_inst_ced00b_idx')],
            },
        ),
    ]
